datatransfer:
  source-table: BANCS_MIN_CLNA
  target-tables:
    - TRANSFERACCOUNT
    - CUSTSETTRANSACCT

testtable:
  prepare-test-data: true
  data-copy-limit: 50
  tables-to-copy:
    - TRANSFERACCOUNT
    - CUSTSETTRANSACCT
  test-table-suffix: "_TEST"

# Datasource definitions should go here (example placeholders)
# main datasource and lookup datasource can point to same DB or different ones.
# In production these will be your real DB connections.
spring:
  datasource:
    # This is for a single default DataSource; for two DataSources you will create beans manually.
    url: jdbc:oracle:thin:@//main-host:1521/ORCLPDB1
    username: MAIN_USER
    password: MAIN_PASS