datatransfer:
  batch-size: 500
  fetch-size: 1000
  xref-replace-bsb: "812"
  update-issync-after-insert: false
  prepare-test-data: false   # UT: set true to create test tables and remap target table names
  source-table: BANCS_MIN_CLNA
  lookup-table: BANCS_SK_CUST_INFO
  xref-table: XREF
  target-zero: TRANSFERACCOUNT
  target-one: CUSTSETTRANSACCT

# Datasource definitions should go here (example placeholders)
# main datasource and lookup datasource can point to same DB or different ones.
# In production these will be your real DB connections.
spring:
  datasource:
    # This is for a single default DataSource; for two DataSources you will create beans manually.
    url: jdbc:oracle:thin:@//main-host:1521/ORCLPDB1
    username: MAIN_USER
    password: MAIN_PASS